use crate::{
    app_session::SessionSaveSnapshot,
    buffer_find::{BufferFindCache, BufferFindScope},
    command_bus_runtime::ShortcutDispatchCache,
    command_palette_items::CommandPaletteQueryMemoryEntry,
    command_palette_overlay::CommandPaletteResultsCache,
    devtools::{CommandTraceEntry, FrameTimingSample, VerboseLogEntry},
    devtools_async_tasks::{AsyncTaskActiveEntry, AsyncTaskTraceEntry},
    devtools_lsp_trace::LspTraceEntry,
    devtools_profile::ProfileSample,
    devtools_repaint_diagnostics::RepaintDiagnosticSample,
    devtools_startup::StartupTimingEntry,
    editor_bracket_overlay_cache::EditorBracketOverlayCache,
    editor_match_highlight_cache::EditorMatchHighlightCache,
    editor_vim_key_events::{
        EditorVimCharFind, EditorVimLastChange, EditorVimMode, EditorVimPendingKey,
        EditorVimRegister,
    },
    explorer::{ExplorerDeleteTarget, ExplorerFileAction},
    explorer_tree_panel::ExplorerDirectorySnapshot,
    folding::FoldedRange,
    fs_watcher::FileWatcher,
    git_diff_state::{DiffBufferSource, DiffCacheEntry, DiffCacheRequestKey},
    gpu_acceleration_prompt::GpuAccelerationPrompt,
    history::{ClosedFileEntry, NavigationLocation},
    image_preview::ImagePreviewState,
    large_file_mode::LineRenderProtectionCacheEntry,
    lsp_client::LspClientHandle,
    lsp_completion_resolve::CompletionPreviewResolveKey,
    lsp_diagnostics_batch::PendingLspDiagnosticsBatch,
    lsp_hover_cache::LspHoverCacheEntry,
    lsp_progress::LspProgressKey,
    lsp_rename_preview::LspRenamePreviewRow,
    lsp_workspace_symbol_ranking::WorkspaceSymbolQueryMemoryEntry,
    merge_conflict_cache::MergeConflictCacheEntry,
    minimap::{MinimapLineLengthCache, MinimapSectionHeaderCache},
    panel_layout::PanelPlacement,
    persistence::{BufferHistoryState, BufferViewState, PaneBufferViewState},
    project_search_state::ProjectSearchQuery,
    quick_open::QuickOpenResultsCache,
    session_state::EditorPane,
    snippet_session::SnippetSession,
    source_control_panel::{SourceControlSortMode, SourceControlViewMode},
    startup_tasks::{GitScanRootCacheEntry, PendingWorkspaceRefresh},
    syntax::SyntaxHighlighter,
    syntax_tree_cache::TreeSitterSyntaxCache,
    terminal::TerminalPane,
    transient_state::{
        EditorImePreedit, EditorInertialScroll, EditorMiddleClickScroll, EditorSelectionDrag,
        FileJump, LspHoverPopup, LspHoverRequestTarget, LspSignatureHelpPopup,
        PendingEditorFileDrop, PendingExit, PendingLspHover, PendingSourceControlCommitSave,
        PendingSourceControlDiscard, PendingSourceControlEmptyCommit,
        PendingSourceControlProtectedBranchCommit, PendingSourceControlSmartCommit,
        PendingSourceControlStashSave, PendingWorkspaceSwitch,
    },
    ui_event_channel::{Receiver, Sender},
    ui_events::UiEvent,
    workspace_state::PaneId,
    workspace_tasks_runtime::RunningWorkspaceTask,
};
use fuzzy_matcher::skim::SkimMatcherV2;
use kuroya_core::{
    BufferId, Command, CommandBus, DiagnosticSet, EditorSettings, GitBlameLine, GitBranch,
    GitChangeStage, GitCommitSummary, GitDiffHunk, GitSnapshot, GitStashEntry,
    LspCallHierarchyCall, LspCallHierarchyItem, LspCodeAction, LspCodeLens, LspCompletionItem,
    LspDocumentHighlight, LspDocumentSymbol, LspFoldingRange, LspInlayHint, LspReference,
    LspSemanticToken, LspTextEdit, LspTypeHierarchyItem, LspWorkspaceSymbol, PluginActivationState,
    PluginCommandRegistry, PluginDescriptor, PluginDiscoveryError, PluginLanguageRegistry,
    PluginRuntimeRegistry, PluginSyntaxRegistry, PluginThemeRegistry, ProjectIndex,
    ProjectSearchIndex, SearchResult, TextBuffer, Workspace, WorkspaceTask, WorkspaceTaskKind,
};
use std::{
    collections::{HashMap, HashSet, VecDeque},
    path::PathBuf,
    sync::{Arc, atomic::AtomicU64},
    time::Instant,
};
use tokio::runtime::Runtime;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct PendingFormatOnSave {
    pub(crate) save_path: PathBuf,
    pub(crate) format_path: PathBuf,
    pub(crate) version: u64,
    pub(crate) request_id: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub(crate) struct PendingFileReload {
    pub(crate) request_id: u64,
    pub(crate) path: PathBuf,
    pub(crate) version: u64,
    pub(crate) force_dirty: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct QueuedFileReload {
    pub(crate) path: PathBuf,
    pub(crate) force_dirty: bool,
}

pub(crate) struct KuroyaApp {
    pub(crate) runtime: Runtime,
    pub(crate) tx: Sender<UiEvent>,
    pub(crate) rx: Receiver<UiEvent>,
    pub(crate) workspace: Workspace,
    pub(crate) workspace_placeholder: bool,
    pub(crate) workspace_event_generation: u64,
    pub(crate) index: ProjectIndex,
    pub(crate) project_search_index: Arc<ProjectSearchIndex>,
    pub(crate) project_search_index_generation: u64,
    pub(crate) command_bus: CommandBus,
    pub(crate) shortcut_dispatch_cache: ShortcutDispatchCache,
    pub(crate) settings: EditorSettings,
    pub(crate) highlighter: SyntaxHighlighter,
    pub(crate) syntax_tree_cache: TreeSitterSyntaxCache,
    pub(crate) matcher: SkimMatcherV2,
    pub(crate) buffers: Vec<TextBuffer>,
    pub(crate) virtual_buffer_labels: HashMap<BufferId, String>,
    pub(crate) diff_buffer_sources: HashMap<BufferId, DiffBufferSource>,
    pub(crate) diff_cache: HashMap<BufferId, DiffCacheEntry>,
    pub(crate) diff_cache_pending: HashMap<DiffCacheRequestKey, Instant>,
    pub(crate) merge_conflict_cache: HashMap<BufferId, MergeConflictCacheEntry>,
    pub(crate) editor_bracket_overlay_cache: EditorBracketOverlayCache,
    pub(crate) editor_match_highlight_cache: EditorMatchHighlightCache,
    pub(crate) minimap_line_length_cache: MinimapLineLengthCache,
    pub(crate) minimap_section_header_cache: MinimapSectionHeaderCache,
    pub(crate) line_render_protection_cache: HashMap<BufferId, LineRenderProtectionCacheEntry>,
    pub(crate) external_change_buffers: HashSet<BufferId>,
    pub(crate) external_change_generation: u64,
    pub(crate) file_reload_next_request_id: u64,
    pub(crate) in_flight_reloads: HashMap<BufferId, PendingFileReload>,
    pub(crate) queued_file_reloads: HashMap<BufferId, QueuedFileReload>,
    pub(crate) canceled_file_reloads: HashSet<(BufferId, PendingFileReload)>,
    pub(crate) canceled_file_reload_order: VecDeque<(BufferId, PendingFileReload)>,
    pub(crate) lossy_decoded_buffers: HashSet<BufferId>,
    pub(crate) binary_preview_buffers: HashSet<BufferId>,
    pub(crate) image_preview_buffers: HashMap<BufferId, ImagePreviewState>,
    pub(crate) manual_read_only_buffers: HashSet<BufferId>,
    pub(crate) explorer_expanded: HashSet<PathBuf>,
    pub(crate) explorer_revealed_path: Option<PathBuf>,
    pub(crate) explorer_directory_cache: HashMap<PathBuf, ExplorerDirectorySnapshot>,
    pub(crate) explorer_compare_path: Option<PathBuf>,
    pub(crate) explorer_file_action: Option<ExplorerFileAction>,
    pub(crate) explorer_file_input: String,
    pub(crate) explorer_delete_target: Option<ExplorerDeleteTarget>,
    pub(crate) panes: Vec<EditorPane>,
    pub(crate) active_pane: PaneId,
    pub(crate) focused_pane: Option<PaneId>,
    pub(crate) next_pane_id: PaneId,
    pub(crate) editor_content_width: f32,
    pub(crate) active: Option<BufferId>,
    pub(crate) next_buffer_id: BufferId,
    pub(crate) status: String,
    pub(crate) update_check_in_flight: bool,
    pub(crate) quick_open: bool,
    pub(crate) quick_open_query: String,
    pub(crate) quick_open_selected: usize,
    pub(crate) quick_open_recent_files: VecDeque<PathBuf>,
    pub(crate) quick_open_query_memory: VecDeque<crate::quick_open::QuickOpenQueryMemoryEntry>,
    pub(crate) quick_open_results_cache: Option<QuickOpenResultsCache>,
    pub(crate) buffer_find_open: bool,
    pub(crate) buffer_find_query: String,
    pub(crate) buffer_find_replacement: String,
    pub(crate) buffer_find_query_history: VecDeque<String>,
    pub(crate) buffer_find_query_history_cursor: Option<usize>,
    pub(crate) buffer_find_query_history_draft: Option<String>,
    pub(crate) buffer_find_replacement_history: VecDeque<String>,
    pub(crate) buffer_find_replacement_history_cursor: Option<usize>,
    pub(crate) buffer_find_replacement_history_draft: Option<String>,
    pub(crate) buffer_find_match: usize,
    pub(crate) buffer_find_case_sensitive: bool,
    pub(crate) buffer_find_whole_word: bool,
    pub(crate) buffer_find_regex: bool,
    pub(crate) buffer_find_preserve_case: bool,
    pub(crate) buffer_find_scope: Option<BufferFindScope>,
    pub(crate) buffer_find_cache: BufferFindCache,
    pub(crate) goto_line_open: bool,
    pub(crate) goto_line_input: String,
    pub(crate) command_palette: bool,
    pub(crate) command_query: String,
    pub(crate) command_selected: usize,
    pub(crate) command_recent: VecDeque<Command>,
    pub(crate) command_query_memory: VecDeque<CommandPaletteQueryMemoryEntry>,
    pub(crate) command_palette_results_cache: Option<CommandPaletteResultsCache>,
    pub(crate) open_workspace_picker_in_flight: bool,
    pub(crate) open_workspace_picker_request_id: u64,
    pub(crate) open_workspace_open: bool,
    pub(crate) open_workspace_path: String,
    pub(crate) save_as_open: bool,
    pub(crate) save_as_buffer: Option<BufferId>,
    pub(crate) save_as_path: String,
    pub(crate) settings_panel_open: bool,
    pub(crate) settings_panel_section: usize,
    pub(crate) settings_panel_draft: EditorSettings,
    pub(crate) settings_editor_font_path: String,
    pub(crate) settings_ui_font_path: String,
    pub(crate) theme_picker_open: bool,
    pub(crate) theme_picker_selected: usize,
    pub(crate) keybindings_open: bool,
    pub(crate) keybindings_query: String,
    pub(crate) keybindings_selected: usize,
    pub(crate) keybinding_capture_command: Option<Command>,
    pub(crate) dirty_close_buffer: Option<BufferId>,
    pub(crate) dirty_reload_buffer: Option<BufferId>,
    pub(crate) save_conflict_buffer: Option<BufferId>,
    pub(crate) pending_close_buffers: Vec<BufferId>,
    pub(crate) close_after_save: Option<BufferId>,
    pub(crate) pending_workspace_switch: Option<PendingWorkspaceSwitch>,
    pub(crate) pending_exit: Option<PendingExit>,
    pub(crate) pending_editor_file_drop: Option<PendingEditorFileDrop>,
    pub(crate) pending_source_control_discard: Option<PendingSourceControlDiscard>,
    pub(crate) pending_source_control_smart_commit: Option<PendingSourceControlSmartCommit>,
    pub(crate) pending_source_control_empty_commit: Option<PendingSourceControlEmptyCommit>,
    pub(crate) pending_source_control_protected_branch_commit:
        Option<PendingSourceControlProtectedBranchCommit>,
    pub(crate) pending_source_control_commit_save: Option<PendingSourceControlCommitSave>,
    pub(crate) pending_source_control_stash_save: Option<PendingSourceControlStashSave>,
    pub(crate) exit_confirmed: bool,
    pub(crate) shutdown_prepared: bool,
    pub(crate) in_flight_saves: HashSet<BufferId>,
    pub(crate) queued_save_paths: HashMap<BufferId, PathBuf>,
    pub(crate) pending_format_on_save: HashMap<BufferId, PendingFormatOnSave>,
    pub(crate) pending_format_on_save_started: HashMap<BufferId, Instant>,
    pub(crate) pending_format_on_save_retries: HashMap<BufferId, u8>,
    pub(crate) canceled_formatting_request_ids: HashSet<u64>,
    pub(crate) canceled_formatting_request_order: VecDeque<u64>,
    pub(crate) format_on_save_overwrite_external_change: HashSet<BufferId>,
    pub(crate) formatting_next_request_id: u64,
    pub(crate) format_on_save_bypass: HashSet<BufferId>,
    pub(crate) pending_open_paths: HashSet<PathBuf>,
    pub(crate) pending_pane_paths: HashMap<PaneId, PathBuf>,
    pub(crate) pending_view_states: HashMap<PathBuf, BufferViewState>,
    pub(crate) pending_pane_view_states: HashMap<PaneId, PaneBufferViewState>,
    pub(crate) pending_history_states: HashMap<PathBuf, BufferHistoryState>,
    pub(crate) explorer_width: f32,
    pub(crate) project_search: bool,
    pub(crate) project_search_placement: PanelPlacement,
    pub(crate) project_search_width: f32,
    pub(crate) project_search_query: String,
    pub(crate) project_search_result: SearchResult,
    pub(crate) project_search_result_query: String,
    pub(crate) project_search_result_index_generation: u64,
    pub(crate) project_search_result_case_sensitive: bool,
    pub(crate) project_search_result_whole_word: bool,
    pub(crate) project_search_result_include_globs: Vec<String>,
    pub(crate) project_search_result_exclude_globs: Vec<String>,
    pub(crate) project_search_case_sensitive: bool,
    pub(crate) project_search_whole_word: bool,
    pub(crate) project_search_include: String,
    pub(crate) project_search_exclude: String,
    pub(crate) project_search_recent: VecDeque<ProjectSearchQuery>,
    pub(crate) project_search_selected: usize,
    pub(crate) project_search_next_request_id: u64,
    pub(crate) project_search_active_request_id: u64,
    pub(crate) project_search_cancel_generation: Arc<AtomicU64>,
    pub(crate) terminal: TerminalPane,
    pub(crate) terminal_height: f32,
    pub(crate) terminal_open_height_pending: bool,
    pub(crate) watcher: Option<FileWatcher>,
    pub(crate) git: GitSnapshot,
    pub(crate) git_scan_root_cache: Option<GitScanRootCacheEntry>,
    pub(crate) workspace_index_next_request_id: u64,
    pub(crate) workspace_index_active_request_id: u64,
    pub(crate) workspace_index_in_flight_request_id: Option<u64>,
    pub(crate) workspace_index_refresh_queued: bool,
    pub(crate) project_index_generation: u64,
    pub(crate) git_scan_next_request_id: u64,
    pub(crate) git_scan_active_request_id: u64,
    pub(crate) git_scan_in_flight_request_id: Option<u64>,
    pub(crate) git_scan_refresh_queued: bool,
    pub(crate) pending_workspace_refresh: Option<PendingWorkspaceRefresh>,
    pub(crate) source_control: bool,
    pub(crate) source_control_placement: PanelPlacement,
    pub(crate) source_control_width: f32,
    pub(crate) source_control_query: String,
    pub(crate) source_control_view: SourceControlViewMode,
    pub(crate) source_control_sort: SourceControlSortMode,
    pub(crate) source_control_commit_message: String,
    pub(crate) source_control_commit_history: Vec<String>,
    pub(crate) source_control_commit_history_index: Option<usize>,
    pub(crate) source_control_commit_next_request_id: u64,
    pub(crate) source_control_commit_active_request_id: u64,
    pub(crate) source_control_commit_in_flight_request_ids: HashSet<u64>,
    pub(crate) source_control_selected: usize,
    pub(crate) source_control_unstaged_collapsed: bool,
    pub(crate) source_control_untracked_collapsed: bool,
    pub(crate) source_control_staged_collapsed: bool,
    pub(crate) source_control_branch_picker_open: bool,
    pub(crate) source_control_branch_query: String,
    pub(crate) source_control_branch_rename_from: Option<String>,
    pub(crate) source_control_branches: Vec<GitBranch>,
    pub(crate) source_control_branch_selected: usize,
    pub(crate) source_control_branch_next_request_id: u64,
    pub(crate) source_control_branch_active_request_id: u64,
    pub(crate) source_control_branch_in_flight_request_id: Option<u64>,
    pub(crate) source_control_branch_reload_queued: bool,
    pub(crate) source_control_branch_operation_next_request_id: u64,
    pub(crate) source_control_branch_operation_active_request_id: u64,
    pub(crate) source_control_branch_operation_in_flight_request_ids: HashSet<u64>,
    pub(crate) source_control_history_open: bool,
    pub(crate) source_control_history_query: String,
    pub(crate) source_control_history: Vec<GitCommitSummary>,
    pub(crate) source_control_history_selected: usize,
    pub(crate) source_control_history_next_request_id: u64,
    pub(crate) source_control_history_active_request_id: u64,
    pub(crate) source_control_history_in_flight_request_id: Option<u64>,
    pub(crate) source_control_history_reload_queued: bool,
    pub(crate) source_control_history_loading: bool,
    pub(crate) source_control_history_requested_limit: usize,
    pub(crate) source_control_history_has_more: bool,
    pub(crate) pending_restored_git_history_load: bool,
    pub(crate) source_control_stashes_open: bool,
    pub(crate) source_control_stash_message: String,
    pub(crate) source_control_stashes: Vec<GitStashEntry>,
    pub(crate) source_control_stash_selected: usize,
    pub(crate) source_control_stashes_next_request_id: u64,
    pub(crate) source_control_stashes_active_request_id: u64,
    pub(crate) source_control_stashes_in_flight_request_id: Option<u64>,
    pub(crate) source_control_stashes_reload_queued: bool,
    pub(crate) pending_restored_git_stashes_load: bool,
    pub(crate) source_control_hunks_open: bool,
    pub(crate) source_control_hunk_path: Option<PathBuf>,
    pub(crate) source_control_hunk_stage: GitChangeStage,
    pub(crate) source_control_hunks: Vec<GitDiffHunk>,
    pub(crate) source_control_hunk_selected: usize,
    pub(crate) source_control_hunks_next_request_id: u64,
    pub(crate) source_control_hunks_active_request_id: u64,
    pub(crate) source_control_hunks_in_flight_request_id: Option<u64>,
    pub(crate) source_control_hunks_reload_queued: bool,
    pub(crate) source_control_diff_open_next_request_id: u64,
    pub(crate) source_control_diff_open_active_request_id: u64,
    pub(crate) virtual_diff_open_next_request_id: u64,
    pub(crate) virtual_diff_open_active_request_id: u64,
    pub(crate) virtual_revision_open_next_request_id: u64,
    pub(crate) virtual_revision_open_active_request_id: u64,
    pub(crate) source_control_patch_copy_next_request_id: u64,
    pub(crate) source_control_patch_copy_active_request_id: u64,
    pub(crate) source_control_blame_next_request_id: u64,
    pub(crate) source_control_blame_active_request_id: u64,
    pub(crate) source_control_blame_active_request_ids: HashMap<PathBuf, u64>,
    pub(crate) source_control_blame_in_flight_request_ids: HashMap<PathBuf, u64>,
    pub(crate) source_control_blame_reload_queued_paths: HashSet<PathBuf>,
    pub(crate) source_control_blame_open_view_paths: HashSet<PathBuf>,
    pub(crate) source_control_blame_load_opens_view: bool,
    pub(crate) source_control_blame_pending_path: Option<PathBuf>,
    pub(crate) source_control_blame_ignore_whitespace: bool,
    pub(crate) source_control_blame_cache: HashMap<PathBuf, Vec<GitBlameLine>>,
    pub(crate) diagnostics: DiagnosticSet,
    pub(crate) static_diagnostics_next_request_id: u64,
    pub(crate) static_diagnostics_active_request_ids: HashMap<BufferId, u64>,
    pub(crate) static_diagnostics_in_flight_request_ids: HashMap<BufferId, u64>,
    pub(crate) static_diagnostics_reload_queued: HashSet<BufferId>,
    pub(crate) pending_lsp_diagnostics: PendingLspDiagnosticsBatch,
    pub(crate) diagnostics_panel: bool,
    pub(crate) diagnostics_panel_placement: PanelPlacement,
    pub(crate) diagnostics_panel_width: f32,
    pub(crate) diagnostics_panel_selected: usize,
    pub(crate) devtools_open: bool,
    pub(crate) gpu_acceleration_prompt: Option<GpuAccelerationPrompt>,
    pub(crate) gpu_acceleration_prompt_dismissed: bool,
    pub(crate) startup_timings: Vec<StartupTimingEntry>,
    pub(crate) frame_timings: VecDeque<FrameTimingSample>,
    pub(crate) repaint_diagnostics: VecDeque<RepaintDiagnosticSample>,
    pub(crate) next_repaint_diagnostic_id: u64,
    pub(crate) last_repaint_diagnostic_at: Option<Instant>,
    pub(crate) command_trace: VecDeque<CommandTraceEntry>,
    pub(crate) next_command_trace_id: u64,
    pub(crate) verbose_log: VecDeque<VerboseLogEntry>,
    pub(crate) next_verbose_log_id: u64,
    pub(crate) profile_samples: VecDeque<ProfileSample>,
    pub(crate) next_profile_sample_id: u64,
    pub(crate) async_task_trace: VecDeque<AsyncTaskTraceEntry>,
    pub(crate) active_async_tasks: VecDeque<AsyncTaskActiveEntry>,
    pub(crate) next_async_task_id: u64,
    pub(crate) lsp_trace: VecDeque<LspTraceEntry>,
    pub(crate) next_lsp_trace_id: u64,
    pub(crate) symbols_panel: bool,
    pub(crate) symbols_panel_placement: PanelPlacement,
    pub(crate) symbols_panel_width: f32,
    pub(crate) document_symbols: Vec<LspDocumentSymbol>,
    pub(crate) document_symbols_path: Option<PathBuf>,
    pub(crate) document_symbols_selected: usize,
    pub(crate) workspace_symbols_open: bool,
    pub(crate) workspace_symbol_query: String,
    pub(crate) workspace_symbol_submitted_query: String,
    pub(crate) workspace_symbol_submitted_path: Option<PathBuf>,
    pub(crate) workspace_symbols: Vec<LspWorkspaceSymbol>,
    pub(crate) workspace_symbols_selected: usize,
    pub(crate) workspace_symbol_query_memory: VecDeque<WorkspaceSymbolQueryMemoryEntry>,
    pub(crate) workspace_tasks_open: bool,
    pub(crate) workspace_tasks: Vec<WorkspaceTask>,
    pub(crate) workspace_tasks_selected: usize,
    pub(crate) workspace_tasks_next_request_id: u64,
    pub(crate) workspace_tasks_active_request_id: u64,
    pub(crate) workspace_tasks_in_flight_request_id: Option<u64>,
    pub(crate) workspace_tasks_reload_queued: bool,
    pub(crate) workspace_tasks_loading: bool,
    pub(crate) workspace_tasks_loaded: bool,
    pub(crate) pending_workspace_task_kind: Option<WorkspaceTaskKind>,
    pub(crate) running_workspace_tasks: Vec<RunningWorkspaceTask>,
    pub(crate) plugins: Vec<PluginDescriptor>,
    pub(crate) plugin_errors: Vec<PluginDiscoveryError>,
    pub(crate) plugin_runtimes: PluginRuntimeRegistry,
    pub(crate) plugin_activations: PluginActivationState,
    pub(crate) plugin_commands: PluginCommandRegistry,
    pub(crate) plugin_languages: PluginLanguageRegistry,
    pub(crate) plugin_themes: PluginThemeRegistry,
    pub(crate) plugin_syntaxes: PluginSyntaxRegistry,
    pub(crate) workspace_plugins_next_request_id: u64,
    pub(crate) workspace_plugins_active_request_id: u64,
    pub(crate) workspace_plugins_in_flight_request_id: Option<u64>,
    pub(crate) workspace_plugins_reload_queued: bool,
    pub(crate) pending_workspace_plugin_reload: Option<Instant>,
    pub(crate) completion_open: bool,
    pub(crate) completion_items: Vec<LspCompletionItem>,
    pub(crate) completion_buffer_id: Option<BufferId>,
    pub(crate) completion_path: Option<PathBuf>,
    pub(crate) completion_version: Option<u64>,
    pub(crate) completion_line: usize,
    pub(crate) completion_column: usize,
    pub(crate) completion_prefix: String,
    pub(crate) completion_selected: usize,
    pub(crate) completion_preview_resolve_in_flight: Vec<CompletionPreviewResolveKey>,
    pub(crate) completion_preview_resolve_recent_attempts: Vec<CompletionPreviewResolveKey>,
    pub(crate) completion_recent_labels: VecDeque<String>,
    pub(crate) completion_recent_prefix_labels: VecDeque<(String, String)>,
    pub(crate) snippet_session: Option<SnippetSession>,
    pub(crate) ime_preedit: Option<EditorImePreedit>,
    pub(crate) pending_completion_requests: HashMap<BufferId, Instant>,
    pub(crate) pending_signature_help_requests: HashMap<BufferId, Instant>,
    pub(crate) pending_format_on_type_requests: HashMap<BufferId, Instant>,
    pub(crate) signature_help: Option<LspSignatureHelpPopup>,
    pub(crate) code_actions_open: bool,
    pub(crate) code_actions: Vec<LspCodeAction>,
    pub(crate) code_actions_buffer_id: Option<BufferId>,
    pub(crate) code_actions_path: Option<PathBuf>,
    pub(crate) code_actions_version: Option<u64>,
    pub(crate) code_actions_line: usize,
    pub(crate) code_actions_column: usize,
    pub(crate) code_actions_selected: usize,
    pub(crate) references_open: bool,
    pub(crate) references: Vec<LspReference>,
    pub(crate) references_path: Option<PathBuf>,
    pub(crate) references_line: usize,
    pub(crate) references_column: usize,
    pub(crate) references_selected: usize,
    pub(crate) call_hierarchy_open: bool,
    pub(crate) call_hierarchy_root: Option<LspCallHierarchyItem>,
    pub(crate) call_hierarchy_incoming: Vec<LspCallHierarchyCall>,
    pub(crate) call_hierarchy_outgoing: Vec<LspCallHierarchyCall>,
    pub(crate) call_hierarchy_selected: usize,
    pub(crate) call_hierarchy_path: Option<PathBuf>,
    pub(crate) call_hierarchy_line: usize,
    pub(crate) call_hierarchy_column: usize,
    pub(crate) type_hierarchy_open: bool,
    pub(crate) type_hierarchy_root: Option<LspTypeHierarchyItem>,
    pub(crate) type_hierarchy_supertypes: Vec<LspTypeHierarchyItem>,
    pub(crate) type_hierarchy_subtypes: Vec<LspTypeHierarchyItem>,
    pub(crate) type_hierarchy_selected: usize,
    pub(crate) type_hierarchy_path: Option<PathBuf>,
    pub(crate) type_hierarchy_line: usize,
    pub(crate) type_hierarchy_column: usize,
    pub(crate) lsp_clients: HashMap<String, LspClientHandle>,
    pub(crate) lsp_unavailable: HashSet<String>,
    pub(crate) lsp_restart_attempts: HashMap<String, u8>,
    pub(crate) pending_lsp_restarts: HashMap<String, Instant>,
    pub(crate) pending_lsp_symbol_refreshes: HashMap<BufferId, Instant>,
    pub(crate) lsp_progress_titles: HashMap<LspProgressKey, String>,
    pub(crate) pending_lsp_hover: Option<PendingLspHover>,
    pub(crate) lsp_hover_request: Option<LspHoverRequestTarget>,
    pub(crate) lsp_hover: Option<LspHoverPopup>,
    pub(crate) lsp_hover_cache: VecDeque<LspHoverCacheEntry>,
    pub(crate) document_highlights_path: Option<PathBuf>,
    pub(crate) document_highlights: Vec<LspDocumentHighlight>,
    pub(crate) folding_ranges: HashMap<PathBuf, Vec<LspFoldingRange>>,
    pub(crate) inlay_hints: HashMap<PathBuf, Vec<LspInlayHint>>,
    pub(crate) code_lenses: HashMap<PathBuf, Vec<LspCodeLens>>,
    pub(crate) semantic_tokens: HashMap<PathBuf, Vec<LspSemanticToken>>,
    pub(crate) folded_ranges: HashMap<PathBuf, Vec<FoldedRange>>,
    pub(crate) pending_fold_line: Option<(PathBuf, usize)>,
    pub(crate) lsp_rename_open: bool,
    pub(crate) lsp_rename_input: String,
    pub(crate) lsp_rename_preview_open: bool,
    pub(crate) lsp_rename_preview_new_name: String,
    pub(crate) lsp_rename_preview_edits: Vec<LspTextEdit>,
    pub(crate) lsp_rename_preview_rows: Vec<LspRenamePreviewRow>,
    pub(crate) lsp_rename_preview_versions: HashMap<PathBuf, u64>,
    pub(crate) recent_projects: Vec<PathBuf>,
    pub(crate) trusted_workspaces: Vec<PathBuf>,
    pub(crate) workspace_trusted: bool,
    pub(crate) pending_active_path: Option<PathBuf>,
    pub(crate) pending_file_jump: Option<FileJump>,
    pub(crate) navigation_back: VecDeque<NavigationLocation>,
    pub(crate) navigation_forward: VecDeque<NavigationLocation>,
    pub(crate) closed_files: VecDeque<ClosedFileEntry>,
    pub(crate) pending_scroll_lines: HashMap<BufferId, usize>,
    pub(crate) pending_horizontal_scroll_offsets: HashMap<BufferId, f32>,
    pub(crate) pending_pane_scroll_lines: HashMap<(PaneId, BufferId), usize>,
    pub(crate) pending_pane_horizontal_scroll_offsets: HashMap<(PaneId, BufferId), f32>,
    pub(crate) editor_scroll_offsets: HashMap<(PaneId, BufferId), f32>,
    pub(crate) editor_horizontal_scroll_offsets: HashMap<(PaneId, BufferId), f32>,
    pub(crate) editor_scroll_targets: HashMap<(PaneId, BufferId), f32>,
    pub(crate) editor_inertial_scrolls: HashMap<(PaneId, BufferId), EditorInertialScroll>,
    pub(crate) editor_middle_click_scroll: Option<EditorMiddleClickScroll>,
    pub(crate) editor_selection_drag: Option<EditorSelectionDrag>,
    pub(crate) editor_selection_clipboard: Option<String>,
    pub(crate) editor_vim_mode: EditorVimMode,
    pub(crate) editor_vim_pending_key: Option<EditorVimPendingKey>,
    pub(crate) editor_vim_last_char_find: Option<EditorVimCharFind>,
    pub(crate) editor_vim_unnamed_register: Option<EditorVimRegister>,
    pub(crate) editor_vim_last_change: Option<EditorVimLastChange>,
    pub(crate) editor_defer_match_highlights_for_buffer: Option<BufferId>,
    pub(crate) pending_language_sync: HashMap<BufferId, Instant>,
    pub(crate) session_save_in_flight: Option<PathBuf>,
    pub(crate) queued_session_saves: HashMap<PathBuf, SessionSaveSnapshot>,
    pub(crate) last_autosave: Instant,
    pub(crate) last_autosave_window_focused: bool,
    pub(crate) last_autosave_focused_pane: Option<PaneId>,
    pub(crate) last_session_save: Instant,
    pub(crate) theme_dirty: bool,
    pub(crate) fonts_dirty: bool,
}
