use crate::{
    KuroyaApp,
    app_startup_context::{AppStartupContext, is_empty_startup_workspace_root},
    layout::{
        DIAGNOSTICS_PANEL_DEFAULT_WIDTH, EXPLORER_DEFAULT_WIDTH, PROJECT_SEARCH_DEFAULT_WIDTH,
        SOURCE_CONTROL_DEFAULT_WIDTH, SYMBOLS_PANEL_DEFAULT_WIDTH, TERMINAL_DEFAULT_HEIGHT,
    },
    panel_layout::PanelPlacement,
    session_state::EditorPane,
    source_control_panel::{
        source_control_sort_mode_from_setting, source_control_view_mode_from_setting,
    },
    syntax::SyntaxHighlighter,
    syntax_tree_cache::TreeSitterSyntaxCache,
    update_checker::initial_automatic_update_check_at,
    workspace_trust::workspace_is_trusted,
};
use fuzzy_matcher::skim::SkimMatcherV2;
use kuroya_core::{
    CommandBus, DiagnosticSet, GitChangeStage, GitSnapshot, ProjectIndex, SearchResult,
};
use std::{
    collections::{HashMap, HashSet, VecDeque},
    sync::{Arc, atomic::AtomicU64},
};

impl KuroyaApp {
    pub(crate) fn from_startup_context(context: AppStartupContext) -> Self {
        let AppStartupContext {
            runtime,
            tx,
            rx,
            workspace,
            settings,
            settings_panel_draft,
            settings_editor_font_path,
            settings_ui_font_path,
            theme_picker_selected,
            saved_session: _,
            terminal,
            watcher,
            recent_projects,
            trusted_workspaces,
            now,
            startup_timings,
        } = context;
        let workspace_placeholder = is_empty_startup_workspace_root(&workspace.root);
        let workspace_trusted = workspace_is_trusted(&trusted_workspaces, &workspace.root);
        let source_control_view =
            source_control_view_mode_from_setting(settings.scm_default_view_mode);
        let source_control_sort =
            source_control_sort_mode_from_setting(settings.scm_default_view_sort_key);
        let app_state_vim_keybindings = settings.vim_keybindings;
        let app_state_vim = settings.vim.clone();

        Self {
            runtime,
            tx,
            rx,
            #[cfg(test)]
            app_state_path_override: None,
            workspace,
            workspace_placeholder,
            workspace_event_generation: 0,
            index: ProjectIndex::default(),
            project_search_index_generation: 0,
            command_bus: CommandBus::default(),
            shortcut_dispatch_cache: Default::default(),
            settings,
            app_state_vim_keybindings,
            app_state_vim,
            highlighter: SyntaxHighlighter::new(),
            syntax_tree_cache: TreeSitterSyntaxCache::default(),
            matcher: SkimMatcherV2::default(),
            buffers: Vec::new(),
            virtual_buffer_labels: HashMap::new(),
            diff_buffer_sources: HashMap::new(),
            diff_cache: HashMap::new(),
            diff_cache_pending: HashMap::new(),
            merge_conflict_cache: HashMap::new(),
            editor_bracket_overlay_cache: Default::default(),
            minimap_line_length_cache: Default::default(),
            minimap_section_header_cache: Default::default(),
            line_render_protection_cache: HashMap::new(),
            external_change_buffers: HashSet::new(),
            external_change_generation: 0,
            file_reload_next_request_id: 0,
            in_flight_reloads: HashMap::new(),
            queued_file_reloads: HashMap::new(),
            canceled_file_reloads: HashSet::new(),
            canceled_file_reload_order: VecDeque::new(),
            lossy_decoded_buffers: HashSet::new(),
            binary_preview_buffers: HashSet::new(),
            image_preview_buffers: HashMap::new(),
            dashboard_logo_texture: None,
            manual_read_only_buffers: HashSet::new(),
            explorer_expanded: HashSet::new(),
            explorer_revealed_path: None,
            explorer_directory_cache: HashMap::new(),
            explorer_compare_path: None,
            explorer_file_action: None,
            explorer_file_input: String::new(),
            explorer_delete_target: None,
            panes: vec![EditorPane {
                id: 1,
                active: None,
                weight: 1.0,
            }],
            active_pane: 1,
            focused_pane: None,
            next_pane_id: 2,
            editor_content_width: 0.0,
            active: None,
            next_buffer_id: 1,
            status: if workspace_placeholder {
                "No folder open".to_owned()
            } else {
                "Indexing workspace".to_owned()
            },
            update_check_in_flight: false,
            update_check_manual: false,
            update_download_in_flight: false,
            available_update: None,
            pending_update_install: None,
            next_automatic_update_check_at: initial_automatic_update_check_at(now),
            quick_open: false,
            quick_open_query: String::new(),
            quick_open_selected: 0,
            quick_open_recent_files: VecDeque::new(),
            quick_open_query_memory: VecDeque::new(),
            quick_open_results_cache: None,
            buffer_find_open: false,
            buffer_find_query: String::new(),
            buffer_find_replacement: String::new(),
            buffer_find_query_history: VecDeque::new(),
            buffer_find_query_history_cursor: None,
            buffer_find_query_history_draft: None,
            buffer_find_replacement_history: VecDeque::new(),
            buffer_find_replacement_history_cursor: None,
            buffer_find_replacement_history_draft: None,
            buffer_find_match: 0,
            buffer_find_case_sensitive: false,
            buffer_find_whole_word: false,
            buffer_find_regex: false,
            buffer_find_preserve_case: false,
            buffer_find_scope: None,
            buffer_find_cache: Default::default(),
            goto_line_open: false,
            goto_line_input: String::new(),
            command_palette: false,
            command_query: String::new(),
            command_selected: 0,
            command_recent: VecDeque::new(),
            command_query_memory: VecDeque::new(),
            command_palette_results_cache: None,
            open_workspace_picker_in_flight: false,
            open_workspace_picker_request_id: 0,
            open_workspace_open: false,
            open_workspace_path: String::new(),
            save_as_open: false,
            save_as_buffer: None,
            save_as_path: String::new(),
            settings_panel_open: false,
            settings_panel_section: 0,
            settings_panel_draft,
            settings_editor_font_path,
            settings_ui_font_path,
            theme_picker_open: false,
            theme_picker_selected,
            keybindings_open: false,
            keybindings_query: String::new(),
            keybindings_selected: 0,
            keybinding_capture_command: None,
            keybinding_escape_cancel: None,
            dirty_close_buffer: None,
            dirty_reload_buffer: None,
            save_conflict_buffer: None,
            pending_close_buffers: Vec::new(),
            close_after_save: None,
            pending_workspace_switch: None,
            pending_exit: None,
            pending_editor_file_drop: None,
            pending_source_control_discard: None,
            pending_source_control_smart_commit: None,
            pending_source_control_empty_commit: None,
            pending_source_control_protected_branch_commit: None,
            pending_source_control_commit_save: None,
            pending_source_control_stash_save: None,
            exit_confirmed: false,
            shutdown_prepared: false,
            in_flight_saves: HashSet::new(),
            queued_save_paths: HashMap::new(),
            pending_format_on_save: HashMap::new(),
            pending_format_on_save_started: HashMap::new(),
            pending_format_on_save_retries: HashMap::new(),
            canceled_formatting_request_ids: HashSet::new(),
            canceled_formatting_request_order: VecDeque::new(),
            format_on_save_overwrite_external_change: HashSet::new(),
            formatting_next_request_id: 0,
            format_on_save_bypass: HashSet::new(),
            pending_open_paths: HashSet::new(),
            pending_pane_paths: HashMap::new(),
            pending_view_states: HashMap::new(),
            pending_pane_view_states: HashMap::new(),
            pending_history_states: HashMap::new(),
            explorer_width: EXPLORER_DEFAULT_WIDTH,
            project_search: false,
            project_search_placement: PanelPlacement::default(),
            project_search_width: PROJECT_SEARCH_DEFAULT_WIDTH,
            project_search_query: String::new(),
            project_search_result: SearchResult::default(),
            project_search_result_query: String::new(),
            project_search_result_index_generation: 0,
            project_search_result_case_sensitive: false,
            project_search_result_whole_word: false,
            project_search_result_include_globs: Vec::new(),
            project_search_result_exclude_globs: Vec::new(),
            project_search_case_sensitive: false,
            project_search_whole_word: false,
            project_search_include: String::new(),
            project_search_exclude: String::new(),
            project_search_recent: VecDeque::new(),
            project_search_selected: 0,
            project_search_next_request_id: 0,
            project_search_active_request_id: 0,
            project_search_cancel_generation: Arc::new(AtomicU64::new(0)),
            terminal,
            terminal_height: TERMINAL_DEFAULT_HEIGHT,
            terminal_open_height_pending: false,
            watcher,
            git: GitSnapshot::default(),
            git_scan_root_cache: None,
            workspace_index_next_request_id: 0,
            workspace_index_active_request_id: 0,
            workspace_index_in_flight_request_id: None,
            workspace_index_refresh_queued: false,
            project_index_generation: 0,
            git_scan_next_request_id: 0,
            git_scan_active_request_id: 0,
            git_scan_in_flight_request_id: None,
            git_scan_refresh_queued: false,
            pending_workspace_refresh: None,
            source_control: false,
            source_control_placement: PanelPlacement::default(),
            source_control_width: SOURCE_CONTROL_DEFAULT_WIDTH,
            source_control_query: String::new(),
            source_control_view,
            source_control_sort,
            source_control_commit_message: String::new(),
            source_control_commit_history: Vec::new(),
            source_control_commit_history_index: None,
            source_control_commit_next_request_id: 0,
            source_control_commit_active_request_id: 0,
            source_control_commit_in_flight_request_ids: HashSet::new(),
            source_control_selected: 0,
            source_control_unstaged_collapsed: false,
            source_control_untracked_collapsed: false,
            source_control_staged_collapsed: false,
            source_control_branch_picker_open: false,
            source_control_branch_query: String::new(),
            source_control_branch_rename_from: None,
            source_control_branches: Vec::new(),
            source_control_branch_selected: 0,
            source_control_branch_next_request_id: 0,
            source_control_branch_active_request_id: 0,
            source_control_branch_in_flight_request_id: None,
            source_control_branch_reload_queued: false,
            source_control_branch_operation_next_request_id: 0,
            source_control_branch_operation_active_request_id: 0,
            source_control_branch_operation_in_flight_request_ids: HashSet::new(),
            source_control_history_open: false,
            source_control_history_query: String::new(),
            source_control_history: Vec::new(),
            source_control_history_selected: 0,
            source_control_history_next_request_id: 0,
            source_control_history_active_request_id: 0,
            source_control_history_in_flight_request_id: None,
            source_control_history_reload_queued: false,
            source_control_history_loading: false,
            source_control_history_requested_limit: 0,
            source_control_history_has_more: false,
            pending_restored_git_history_load: false,
            source_control_stashes_open: false,
            source_control_stash_message: String::new(),
            source_control_stashes: Vec::new(),
            source_control_stash_selected: 0,
            source_control_stashes_next_request_id: 0,
            source_control_stashes_active_request_id: 0,
            source_control_stashes_in_flight_request_id: None,
            source_control_stashes_reload_queued: false,
            pending_restored_git_stashes_load: false,
            source_control_hunks_open: false,
            source_control_hunk_path: None,
            source_control_hunk_stage: GitChangeStage::Unstaged,
            source_control_hunks: Vec::new(),
            source_control_hunk_selected: 0,
            source_control_hunks_next_request_id: 0,
            source_control_hunks_active_request_id: 0,
            source_control_hunks_in_flight_request_id: None,
            source_control_hunks_reload_queued: false,
            source_control_diff_open_next_request_id: 0,
            source_control_diff_open_active_request_id: 0,
            virtual_diff_open_next_request_id: 0,
            virtual_diff_open_active_request_id: 0,
            virtual_revision_open_next_request_id: 0,
            virtual_revision_open_active_request_id: 0,
            source_control_patch_copy_next_request_id: 0,
            source_control_patch_copy_active_request_id: 0,
            source_control_blame_next_request_id: 0,
            source_control_blame_active_request_id: 0,
            source_control_blame_active_request_ids: HashMap::new(),
            source_control_blame_in_flight_request_ids: HashMap::new(),
            source_control_blame_reload_queued_paths: HashSet::new(),
            source_control_blame_open_view_paths: HashSet::new(),
            source_control_blame_load_opens_view: false,
            source_control_blame_pending_path: None,
            source_control_blame_ignore_whitespace: false,
            source_control_blame_cache: HashMap::new(),
            diagnostics: DiagnosticSet::default(),
            static_diagnostics_next_request_id: 0,
            static_diagnostics_active_request_ids: HashMap::new(),
            static_diagnostics_in_flight_request_ids: HashMap::new(),
            static_diagnostics_reload_queued: HashSet::new(),
            pending_lsp_diagnostics: Default::default(),
            diagnostics_panel: false,
            diagnostics_panel_placement: PanelPlacement::default(),
            diagnostics_panel_width: DIAGNOSTICS_PANEL_DEFAULT_WIDTH,
            diagnostics_panel_selected: 0,
            devtools_open: false,
            gpu_acceleration_prompt: None,
            gpu_acceleration_prompt_dismissed: false,
            startup_timings,
            frame_timings: VecDeque::new(),
            repaint_diagnostics: VecDeque::new(),
            next_repaint_diagnostic_id: 0,
            last_repaint_diagnostic_at: None,
            command_trace: VecDeque::new(),
            next_command_trace_id: 0,
            verbose_log: VecDeque::new(),
            next_verbose_log_id: 0,
            profile_samples: VecDeque::new(),
            next_profile_sample_id: 0,
            async_task_trace: VecDeque::new(),
            active_async_tasks: VecDeque::new(),
            next_async_task_id: 0,
            lsp_trace: VecDeque::new(),
            next_lsp_trace_id: 0,
            symbols_panel: false,
            symbols_panel_placement: PanelPlacement::default(),
            symbols_panel_width: SYMBOLS_PANEL_DEFAULT_WIDTH,
            document_symbols: Vec::new(),
            document_symbols_path: None,
            document_symbols_selected: 0,
            workspace_symbols_open: false,
            workspace_symbol_query: String::new(),
            workspace_symbol_submitted_query: String::new(),
            workspace_symbol_submitted_path: None,
            workspace_symbols: Vec::new(),
            workspace_symbols_selected: 0,
            workspace_symbol_query_memory: VecDeque::new(),
            workspace_tasks_open: false,
            workspace_tasks: Vec::new(),
            workspace_tasks_selected: 0,
            workspace_tasks_next_request_id: 0,
            workspace_tasks_active_request_id: 0,
            workspace_tasks_in_flight_request_id: None,
            workspace_tasks_reload_queued: false,
            workspace_tasks_loading: false,
            workspace_tasks_loaded: false,
            pending_workspace_task_kind: None,
            running_workspace_tasks: Vec::new(),
            plugins: Vec::new(),
            plugin_errors: Vec::new(),
            plugin_runtimes: Default::default(),
            plugin_activations: Default::default(),
            plugin_commands: Default::default(),
            plugin_languages: Default::default(),
            plugin_themes: Default::default(),
            plugin_syntaxes: Default::default(),
            workspace_plugins_next_request_id: 0,
            workspace_plugins_active_request_id: 0,
            workspace_plugins_in_flight_request_id: None,
            workspace_plugins_reload_queued: false,
            pending_workspace_plugin_reload: None,
            completion_open: false,
            completion_items: Vec::new(),
            completion_buffer_id: None,
            completion_path: None,
            completion_version: None,
            completion_line: 0,
            completion_column: 0,
            completion_prefix: String::new(),
            completion_selected: 0,
            completion_preview_resolve_in_flight: Vec::new(),
            completion_preview_resolve_recent_attempts: Vec::new(),
            completion_recent_labels: VecDeque::new(),
            completion_recent_prefix_labels: VecDeque::new(),
            snippet_session: None,
            ime_preedit: None,
            pending_completion_requests: HashMap::new(),
            pending_signature_help_requests: HashMap::new(),
            pending_format_on_type_requests: HashMap::new(),
            signature_help: None,
            code_actions_open: false,
            code_actions: Vec::new(),
            code_actions_buffer_id: None,
            code_actions_path: None,
            code_actions_version: None,
            code_actions_line: 0,
            code_actions_column: 0,
            code_actions_selected: 0,
            references_open: false,
            references: Vec::new(),
            references_path: None,
            references_line: 0,
            references_column: 0,
            references_selected: 0,
            call_hierarchy_open: false,
            call_hierarchy_root: None,
            call_hierarchy_incoming: Vec::new(),
            call_hierarchy_outgoing: Vec::new(),
            call_hierarchy_selected: 0,
            call_hierarchy_path: None,
            call_hierarchy_line: 0,
            call_hierarchy_column: 0,
            type_hierarchy_open: false,
            type_hierarchy_root: None,
            type_hierarchy_supertypes: Vec::new(),
            type_hierarchy_subtypes: Vec::new(),
            type_hierarchy_selected: 0,
            type_hierarchy_path: None,
            type_hierarchy_line: 0,
            type_hierarchy_column: 0,
            lsp_clients: HashMap::new(),
            lsp_unavailable: HashSet::new(),
            lsp_restart_attempts: HashMap::new(),
            pending_lsp_restarts: HashMap::new(),
            pending_lsp_symbol_refreshes: HashMap::new(),
            lsp_progress_titles: HashMap::new(),
            pending_lsp_hover: None,
            lsp_hover_request: None,
            lsp_hover: None,
            lsp_hover_cache: VecDeque::new(),
            document_highlights_path: None,
            document_highlights: Vec::new(),
            folding_ranges: HashMap::new(),
            inlay_hints: HashMap::new(),
            code_lenses: HashMap::new(),
            semantic_tokens: HashMap::new(),
            folded_ranges: HashMap::new(),
            pending_fold_line: None,
            lsp_rename_open: false,
            lsp_rename_input: String::new(),
            lsp_rename_preview_open: false,
            lsp_rename_preview_new_name: String::new(),
            lsp_rename_preview_edits: Vec::new(),
            lsp_rename_preview_rows: Vec::new(),
            lsp_rename_preview_versions: HashMap::new(),
            recent_projects,
            trusted_workspaces,
            workspace_trusted,
            pending_active_path: None,
            pending_file_jump: None,
            navigation_back: VecDeque::new(),
            navigation_forward: VecDeque::new(),
            closed_files: VecDeque::new(),
            pending_scroll_lines: HashMap::new(),
            pending_horizontal_scroll_offsets: HashMap::new(),
            pending_pane_scroll_lines: HashMap::new(),
            pending_pane_horizontal_scroll_offsets: HashMap::new(),
            editor_scroll_offsets: HashMap::new(),
            editor_horizontal_scroll_offsets: HashMap::new(),
            editor_scroll_targets: HashMap::new(),
            editor_inertial_scrolls: HashMap::new(),
            editor_middle_click_scroll: None,
            editor_selection_drag: None,
            editor_selection_clipboard: None,
            editor_vim_mode: crate::editor_vim_key_events::EditorVimMode::Normal,
            editor_vim_pending_key: None,
            editor_vim_last_char_find: None,
            editor_vim_unnamed_register: None,
            editor_vim_last_change: None,
            pending_language_sync: HashMap::new(),
            session_save_in_flight: None,
            session_save_in_flight_snapshot: None,
            session_save_in_flight_task: None,
            queued_session_saves: HashMap::new(),
            last_autosave: now,
            last_autosave_window_focused: true,
            last_autosave_focused_pane: None,
            last_session_save: now,
            theme_dirty: false,
            fonts_dirty: false,
        }
    }
}
