use crate::lsp_completion_resolve::CompletionResolveIntent;
use kuroya_core::{
    BufferId, Diagnostic, LspCallHierarchyCall, LspCallHierarchyItem, LspCodeAction, LspCodeLens,
    LspCompletionItem, LspDefinition, LspDocumentHighlight, LspDocumentSymbol, LspFoldingRange,
    LspInlayHint, LspReference, LspRequestId, LspSemanticToken, LspSignatureHelp, LspTextEdit,
    LspTypeHierarchyItem, LspWorkDoneProgress, LspWorkspaceDocumentChange, LspWorkspaceSymbol,
};
use std::collections::BTreeMap;
use std::path::PathBuf;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct LspWorkspaceApplyEditResponseTarget {
    pub(crate) language: String,
    pub(crate) generation: u64,
    pub(crate) request_id: LspRequestId,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct LspWorkspaceApplyEditDiskResponse {
    pub(crate) target: LspWorkspaceApplyEditResponseTarget,
    pub(crate) open_failed: usize,
    pub(crate) open_skipped: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct LspServerResultTarget {
    pub(crate) language: String,
    pub(crate) root: PathBuf,
    pub(crate) generation: u64,
}

#[derive(Debug)]
pub(crate) enum LspUiEvent {
    ServerResult {
        target: LspServerResultTarget,
        event: Box<LspUiEvent>,
    },
    Diagnostics {
        language: String,
        root: PathBuf,
        generation: u64,
        path: PathBuf,
        version: Option<u64>,
        diagnostics: Vec<Diagnostic>,
    },
    BufferSynced {
        id: BufferId,
        path: PathBuf,
        version: u64,
    },
    HoverResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        column: usize,
        contents: Option<String>,
    },
    DocumentHighlightsResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        column: usize,
        highlights: Option<Vec<LspDocumentHighlight>>,
        error: Option<String>,
    },
    DefinitionResult {
        id: BufferId,
        origin_path: PathBuf,
        version: u64,
        origin_line: usize,
        origin_column: usize,
        definition: Option<LspDefinition>,
        error: Option<String>,
    },
    CallHierarchyPrepared {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        column: usize,
        items: Option<Vec<LspCallHierarchyItem>>,
        error: Option<String>,
    },
    CallHierarchyIncomingResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        item: LspCallHierarchyItem,
        calls: Option<Vec<LspCallHierarchyCall>>,
        error: Option<String>,
    },
    CallHierarchyOutgoingResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        item: LspCallHierarchyItem,
        calls: Option<Vec<LspCallHierarchyCall>>,
        error: Option<String>,
    },
    TypeHierarchyPrepared {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        column: usize,
        items: Option<Vec<LspTypeHierarchyItem>>,
        error: Option<String>,
    },
    TypeHierarchySupertypesResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        item: LspTypeHierarchyItem,
        supertypes: Option<Vec<LspTypeHierarchyItem>>,
        error: Option<String>,
    },
    TypeHierarchySubtypesResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        item: LspTypeHierarchyItem,
        subtypes: Option<Vec<LspTypeHierarchyItem>>,
        error: Option<String>,
    },
    ReferencesResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        column: usize,
        references: Option<Vec<LspReference>>,
        error: Option<String>,
    },
    RenameResult {
        id: BufferId,
        origin_path: PathBuf,
        version: u64,
        origin_line: usize,
        origin_column: usize,
        new_name: String,
        edits: Option<Vec<LspTextEdit>>,
        error: Option<String>,
    },
    DocumentSymbolsResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        symbols: Option<Vec<LspDocumentSymbol>>,
        error: Option<String>,
    },
    FoldingRangesResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        ranges: Option<Vec<LspFoldingRange>>,
        error: Option<String>,
    },
    InlayHintsResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        hints: Option<Vec<LspInlayHint>>,
        error: Option<String>,
    },
    CodeLensesResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        lenses: Option<Vec<LspCodeLens>>,
        error: Option<String>,
    },
    CodeLensResolveResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        lens: Option<LspCodeLens>,
        error: Option<String>,
    },
    CodeLensCommandResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        title: String,
        command: String,
        error: Option<String>,
    },
    SemanticTokensResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        tokens: Option<Vec<LspSemanticToken>>,
        error: Option<String>,
    },
    WorkspaceSymbolsResult {
        id: BufferId,
        path: PathBuf,
        query: String,
        symbols: Option<Vec<LspWorkspaceSymbol>>,
        error: Option<String>,
    },
    CompletionResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        column: usize,
        items: Option<Vec<LspCompletionItem>>,
        error: Option<String>,
    },
    CompletionItemResolveResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        column: usize,
        item: Option<Box<LspCompletionItem>>,
        fallback_item: Box<LspCompletionItem>,
        intent: CompletionResolveIntent,
        error: Option<String>,
    },
    SignatureHelpResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        column: usize,
        help: Option<LspSignatureHelp>,
        error: Option<String>,
    },
    FormattingResult {
        request_id: u64,
        id: BufferId,
        path: PathBuf,
        version: u64,
        edits: Option<Vec<LspTextEdit>>,
        error: Option<String>,
    },
    CodeActionsResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        column: usize,
        actions: Option<Vec<LspCodeAction>>,
        error: Option<String>,
    },
    CodeActionResolveResult {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        column: usize,
        action: Option<LspCodeAction>,
        error: Option<String>,
    },
    WorkspaceApplyEditRequest {
        language: String,
        root: PathBuf,
        generation: u64,
        request_id: LspRequestId,
        label: Option<String>,
        edits: Option<Vec<LspTextEdit>>,
        document_changes: Vec<LspWorkspaceDocumentChange>,
        document_versions: BTreeMap<PathBuf, i32>,
        error: Option<String>,
    },
    WorkspaceEditFilesApplied {
        root: PathBuf,
        generation: u64,
        changed: usize,
        failed: Vec<(PathBuf, String)>,
        apply_edit_response: Option<LspWorkspaceApplyEditDiskResponse>,
    },
    WorkDoneProgressCreated {
        token: String,
    },
    WorkDoneProgress {
        language: String,
        root: PathBuf,
        generation: u64,
        progress: LspWorkDoneProgress,
    },
    ServerReady {
        language: String,
        root: PathBuf,
        generation: u64,
    },
    ServerStopped {
        language: String,
        root: PathBuf,
        generation: u64,
    },
    Status {
        language: String,
        root: PathBuf,
        generation: u64,
        message: String,
    },
}
