use crate::lsp_completion_resolve::CompletionResolveIntent;
use kuroya_core::{
    BufferId, Diagnostic, LanguageId, LspCallHierarchyItem, LspCodeAction, LspCodeLens,
    LspCompletionItem, LspRequestId, LspTypeHierarchyItem, TextSnapshot,
};
use serde_json::Value;
use std::{path::PathBuf, sync::Arc};

#[derive(Debug)]
pub(super) enum LspClientCommand {
    DidOpen {
        id: BufferId,
        path: PathBuf,
        language: LanguageId,
        version: u64,
        text: TextSnapshot,
    },
    DidChange {
        id: BufferId,
        path: PathBuf,
        version: u64,
        text: TextSnapshot,
    },
    DidSave {
        path: PathBuf,
    },
    DidClose {
        path: PathBuf,
    },
    Hover {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        character: usize,
    },
    DocumentHighlights {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        character: usize,
    },
    Definition {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        character: usize,
    },
    PrepareCallHierarchy {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        character: usize,
    },
    CallHierarchyIncoming {
        id: BufferId,
        path: PathBuf,
        version: u64,
        item: LspCallHierarchyItem,
    },
    CallHierarchyOutgoing {
        id: BufferId,
        path: PathBuf,
        version: u64,
        item: LspCallHierarchyItem,
    },
    PrepareTypeHierarchy {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        character: usize,
    },
    TypeHierarchySupertypes {
        id: BufferId,
        path: PathBuf,
        version: u64,
        item: LspTypeHierarchyItem,
    },
    TypeHierarchySubtypes {
        id: BufferId,
        path: PathBuf,
        version: u64,
        item: LspTypeHierarchyItem,
    },
    References {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        character: usize,
        include_declaration: bool,
    },
    Rename {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        character: usize,
        new_name: String,
    },
    DocumentSymbols {
        id: BufferId,
        path: PathBuf,
        version: u64,
    },
    FoldingRanges {
        id: BufferId,
        path: PathBuf,
        version: u64,
    },
    InlayHints {
        id: BufferId,
        path: PathBuf,
        version: u64,
        end_line: usize,
        end_character: usize,
    },
    CodeLenses {
        id: BufferId,
        path: PathBuf,
        version: u64,
    },
    ResolveCodeLens {
        id: BufferId,
        path: PathBuf,
        version: u64,
        lens: LspCodeLens,
    },
    ExecuteCommand {
        id: BufferId,
        path: PathBuf,
        version: u64,
        title: String,
        command: String,
        arguments: Option<Arc<Value>>,
    },
    SemanticTokens {
        id: BufferId,
        path: PathBuf,
        version: u64,
    },
    WorkspaceSymbols {
        id: BufferId,
        path: PathBuf,
        query: String,
    },
    Completion {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        character: usize,
    },
    ResolveCompletionItem {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        character: usize,
        item: Box<LspCompletionItem>,
        intent: CompletionResolveIntent,
    },
    SignatureHelp {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        character: usize,
    },
    Formatting {
        request_id: u64,
        id: BufferId,
        path: PathBuf,
        version: u64,
        tab_size: usize,
        insert_spaces: bool,
    },
    CodeActions {
        id: BufferId,
        path: PathBuf,
        version: u64,
        origin_line: usize,
        origin_character: usize,
        start_line: usize,
        start_character: usize,
        end_line: usize,
        end_character: usize,
        diagnostics: Vec<Diagnostic>,
    },
    ResolveCodeAction {
        id: BufferId,
        path: PathBuf,
        version: u64,
        line: usize,
        character: usize,
        action: LspCodeAction,
    },
    ApplyWorkspaceEditResponse {
        request_id: LspRequestId,
        applied: bool,
        failure_reason: Option<String>,
    },
    Shutdown,
}
