pub mod buffer;
pub mod command;
pub mod conflicts;
pub mod diagnostics;
pub mod git;
pub mod keymap;
pub mod lsp;
pub mod plugin;
pub mod project;
pub mod search;
pub mod settings;
pub mod syntax;
pub mod tasks;
pub mod text_match;
mod workspace_paths;

pub use buffer::{
    AutoPairSettings, BufferHistoryEditSnapshot, BufferHistoryEntrySnapshot, BufferHistorySnapshot,
    BufferId, DEFAULT_WORD_SEPARATORS, LineSnapshot, RegexReplaceAllOptions, Selection, TextBuffer,
    TextEdit, TextSnapshot, validate_find_regex,
};
pub use command::{Command, CommandBus};
pub use conflicts::{
    MergeConflict, MergeConflictLineKind, MergeConflictResolution, merge_conflict_at_line,
    merge_conflict_line_kind, merge_conflicts, merge_conflicts_from_lines, resolve_merge_conflict,
};
pub use diagnostics::{Diagnostic, DiagnosticSet, DiagnosticSeverity, analyze_text};
pub use git::{
    DEFAULT_DIFF_CONTEXT_LINES, DEFAULT_DIFF_HIDE_UNCHANGED_REGIONS_MINIMUM_LINE_COUNT,
    DEFAULT_DIFF_HIDE_UNCHANGED_REGIONS_REVEAL_LINE_COUNT, DEFAULT_DIFF_MAX_COMPUTATION_TIME_MS,
    DEFAULT_DIFF_MAX_FILE_SIZE_MB, DEFAULT_GIT_COMMIT_SHORT_HASH_LENGTH,
    DEFAULT_GIT_DETECT_SUBMODULES_LIMIT, DEFAULT_GIT_SIMILARITY_THRESHOLD,
    DEFAULT_GIT_STATUS_LIMIT, DiffAlgorithm, DiffOptions, GitBlameLine, GitBranch, GitChangeStage,
    GitCheckoutType, GitCommitSummary, GitDiffHunk, GitFileStatus, GitLineChangeKind,
    GitRemoteDivergence, GitSmartCommitChanges, GitSnapshot, GitStashEntry, GitStatusCounts,
    GitStatusEntry, GitTimelineDate, MAX_DIFF_CONTEXT_LINES,
    MAX_DIFF_HIDE_UNCHANGED_REGIONS_MINIMUM_LINE_COUNT,
    MAX_DIFF_HIDE_UNCHANGED_REGIONS_REVEAL_LINE_COUNT, MAX_DIFF_MAX_COMPUTATION_TIME_MS,
    MAX_DIFF_MAX_FILE_SIZE_MB, MAX_GIT_COMMIT_SHORT_HASH_LENGTH, MAX_GIT_DETECT_SUBMODULES_LIMIT,
    MAX_GIT_SIMILARITY_THRESHOLD, MAX_GIT_STATUS_LIMIT, MIN_DIFF_CONTEXT_LINES,
    MIN_DIFF_HIDE_UNCHANGED_REGIONS_MINIMUM_LINE_COUNT,
    MIN_DIFF_HIDE_UNCHANGED_REGIONS_REVEAL_LINE_COUNT, MIN_DIFF_MAX_COMPUTATION_TIME_MS,
    MIN_DIFF_MAX_FILE_SIZE_MB, MIN_GIT_COMMIT_SHORT_HASH_LENGTH, MIN_GIT_DETECT_SUBMODULES_LIMIT,
    MIN_GIT_SIMILARITY_THRESHOLD, MIN_GIT_STATUS_LIMIT, apply_stash, blame_file,
    blame_file_for_text_with_options_and_short_hash_length, blame_file_with_options,
    blame_file_with_options_and_short_hash_length, changed_line_kinds_against_head,
    changed_line_kinds_against_head_with_options, changed_lines_against_head,
    changed_lines_against_head_with_options, checkout_branch, checkout_ref,
    clamp_diff_context_lines, clamp_diff_hide_unchanged_regions_minimum_line_count,
    clamp_diff_hide_unchanged_regions_reveal_line_count, clamp_diff_max_computation_time_ms,
    clamp_diff_max_file_size_mb, clamp_git_commit_short_hash_length,
    clamp_git_detect_submodules_limit, clamp_git_similarity_threshold, clamp_git_status_limit,
    commit_changes, commit_changes_with_empty_commit_option, commit_changes_with_options,
    commit_changes_with_short_hash_length, commit_changes_with_user_config_option,
    commit_staged_changes, create_branch, delete_branch, diff_max_file_size_bytes, discard_path,
    discard_paths, discard_worktree_hunk, drop_stash, file_text_at_head, file_text_at_index,
    head_diff_with_text, list_checkout_refs, list_commit_history,
    list_commit_history_with_short_hash_length, list_commit_history_with_timeline_date,
    list_local_branches, list_stashes, list_stashes_with_short_hash_length, path_is_committed,
    pop_stash, rename_branch, save_stash, save_stash_with_short_hash_length,
    save_stash_with_user_config_option, stage_path, stage_paths, stage_worktree_hunk,
    staged_diff_hunks, staged_diff_with_texts, try_unified_diff_between_texts_with_options,
    unified_diff_against_head, unified_diff_against_head_with_options, unified_diff_against_index,
    unified_diff_against_index_with_options, unified_diff_against_worktree,
    unified_diff_against_worktree_with_options, unified_diff_between_texts,
    unified_diff_between_texts_with_options, unified_diff_for_commit, unified_diff_for_stash,
    unstage_path, unstage_paths, unstage_staged_hunk, worktree_diff_hunks,
    worktree_diff_with_index_text,
};
pub use lsp::{
    LspApplyWorkspaceEdit, LspCallHierarchyCall, LspCallHierarchyItem, LspCallHierarchyRange,
    LspCodeAction, LspCodeLens, LspCompletionItem, LspDefinition, LspDocumentHighlight,
    LspDocumentSymbol, LspFoldingRange, LspHover, LspInlayHint, LspParameterInformation,
    LspReference, LspRequestId, LspSemanticToken, LspServerConfig, LspSignatureHelp,
    LspSignatureInformation, LspTextEdit, LspTypeHierarchyItem, LspWireMessage,
    LspWorkDoneProgress, LspWorkDoneProgressCreate, LspWorkDoneProgressKind,
    LspWorkspaceDocumentChange, LspWorkspaceResourceOperation, LspWorkspaceSymbol,
    default_server_configs, lsp_language_id, lsp_language_id_for_path,
    parse_apply_workspace_edit_request, parse_call_hierarchy_incoming_response,
    parse_call_hierarchy_outgoing_response, parse_call_hierarchy_prepare_response,
    parse_code_action_resolve_response, parse_code_action_response,
    parse_code_lens_resolve_response, parse_code_lenses_response,
    parse_completion_item_resolve_response, parse_completion_response, parse_definition_response,
    parse_document_highlight_response, parse_document_symbols_response,
    parse_folding_ranges_response, parse_formatting_response, parse_hover_response,
    parse_inlay_hints_response, parse_lsp_request_id, parse_publish_diagnostics,
    parse_references_response, parse_semantic_tokens_response, parse_signature_help_response,
    parse_type_hierarchy_prepare_response, parse_type_hierarchy_subtypes_response,
    parse_type_hierarchy_supertypes_response, parse_work_done_progress,
    parse_work_done_progress_create, parse_workspace_edit_response,
    parse_workspace_symbols_response, server_config_for_language, server_for_language,
};
pub use plugin::{
    MAX_PLUGIN_SYNTAX_BYTES, PLUGIN_API_VERSION, PluginActivationEvent, PluginActivationRecord,
    PluginActivationState, PluginActivationTrigger, PluginCapabilities, PluginCommandContribution,
    PluginCommandRegistration, PluginCommandRegistry, PluginContributions, PluginDescriptor,
    PluginDiscovery, PluginDiscoveryError, PluginLanguageContribution, PluginLanguageRegistration,
    PluginLanguageRegistry, PluginManifest, PluginRuntimeRegistration, PluginRuntimeRegistry,
    PluginSyntaxContribution, PluginSyntaxRegistration, PluginSyntaxRegistry,
    PluginThemeContribution, PluginThemeRegistration, PluginThemeRegistry,
    discover_workspace_plugins, load_plugin_manifest, load_plugin_theme_settings,
    load_theme_settings_from_path, parse_plugin_manifest_toml, plugin_manifest_path,
    read_plugin_text_file_with_limit, workspace_plugins_dir,
};
pub use project::{
    ProjectEntry, ProjectIndex, ProjectIndexSignature, ProjectSymbol, ProjectSymbolKind, Workspace,
};
pub use search::{SearchMatch, SearchOptions, SearchProgress, SearchResult, SearchStats};
pub use settings::{
    DEFAULT_AUTOSAVE_DELAY_MS, DEFAULT_DIFF_SPLIT_VIEW_DEFAULT_RATIO,
    DEFAULT_EDITOR_ACCESSIBILITY_PAGE_SIZE, DEFAULT_EDITOR_ARIA_LABEL,
    DEFAULT_EDITOR_CODE_LENS_FONT_FAMILY, DEFAULT_EDITOR_CODE_LENS_FONT_SIZE,
    DEFAULT_EDITOR_COLOR_DECORATORS_LIMIT, DEFAULT_EDITOR_CURSOR_HEIGHT,
    DEFAULT_EDITOR_CURSOR_SURROUNDING_LINES, DEFAULT_EDITOR_CURSOR_WIDTH,
    DEFAULT_EDITOR_FAST_SCROLL_SENSITIVITY, DEFAULT_EDITOR_FIND_ADD_EXTRA_SPACE_ON_TOP,
    DEFAULT_EDITOR_FIND_AUTO_FIND_IN_SELECTION, DEFAULT_EDITOR_FIND_GLOBAL_FIND_CLIPBOARD,
    DEFAULT_EDITOR_FIND_SEED_SEARCH_STRING_FROM_SELECTION, DEFAULT_EDITOR_FOLDING_MAXIMUM_REGIONS,
    DEFAULT_EDITOR_FONT_FAMILY, DEFAULT_EDITOR_FONT_LIGATURES, DEFAULT_EDITOR_FONT_VARIATIONS,
    DEFAULT_EDITOR_FONT_WEIGHT, DEFAULT_EDITOR_INLAY_HINTS_FONT_FAMILY,
    DEFAULT_EDITOR_INLAY_HINTS_FONT_SIZE, DEFAULT_EDITOR_INLAY_HINTS_MAXIMUM_LENGTH,
    DEFAULT_EDITOR_LETTER_SPACING, DEFAULT_EDITOR_LINE_DECORATIONS_WIDTH,
    DEFAULT_EDITOR_LINE_HEIGHT, DEFAULT_EDITOR_LINE_NUMBERS_MIN_CHARS,
    DEFAULT_EDITOR_MINIMAP_MARK_SECTION_HEADER_REGEX, DEFAULT_EDITOR_MINIMAP_MAX_COLUMN,
    DEFAULT_EDITOR_MINIMAP_SCALE, DEFAULT_EDITOR_MINIMAP_SECTION_HEADER_FONT_SIZE,
    DEFAULT_EDITOR_MINIMAP_SECTION_HEADER_LETTER_SPACING,
    DEFAULT_EDITOR_MOUSE_WHEEL_SCROLL_SENSITIVITY, DEFAULT_EDITOR_MULTI_CURSOR_LIMIT,
    DEFAULT_EDITOR_OVERVIEW_RULER_LANES, DEFAULT_EDITOR_PADDING_BOTTOM, DEFAULT_EDITOR_PADDING_TOP,
    DEFAULT_EDITOR_PLACEHOLDER, DEFAULT_EDITOR_REVEAL_HORIZONTAL_RIGHT_PADDING,
    DEFAULT_EDITOR_RULER_COLUMN, DEFAULT_EDITOR_SCROLL_BEYOND_LAST_COLUMN,
    DEFAULT_EDITOR_SCROLLBAR_HORIZONTAL_SCROLLBAR_SIZE,
    DEFAULT_EDITOR_SCROLLBAR_VERTICAL_SCROLLBAR_SIZE, DEFAULT_EDITOR_SELECT_ON_LINE_NUMBERS,
    DEFAULT_EDITOR_STICKY_SCROLL_MAX_LINE_COUNT, DEFAULT_EDITOR_STOP_RENDERING_LINE_AFTER,
    DEFAULT_EDITOR_TAB_INDEX, DEFAULT_EDITOR_WORD_WRAP_BREAK_AFTER_CHARACTERS,
    DEFAULT_EDITOR_WORD_WRAP_BREAK_BEFORE_CHARACTERS, DEFAULT_EDITOR_WORD_WRAP_COLUMN,
    DEFAULT_GIT_AUTOFETCH_PERIOD, DEFAULT_GIT_DEFAULT_BRANCH_NAME,
    DEFAULT_GIT_DETECT_WORKTREES_LIMIT, DEFAULT_GIT_INPUT_VALIDATION_LENGTH,
    DEFAULT_GIT_INPUT_VALIDATION_SUBJECT_LENGTH, DEFAULT_GIT_REPOSITORY_SCAN_MAX_DEPTH,
    DEFAULT_GOTO_LOCATION_ALTERNATIVE_DECLARATION_COMMAND,
    DEFAULT_GOTO_LOCATION_ALTERNATIVE_DEFINITION_COMMAND,
    DEFAULT_GOTO_LOCATION_ALTERNATIVE_IMPLEMENTATION_COMMAND,
    DEFAULT_GOTO_LOCATION_ALTERNATIVE_REFERENCE_COMMAND,
    DEFAULT_GOTO_LOCATION_ALTERNATIVE_TESTS_COMMAND,
    DEFAULT_GOTO_LOCATION_ALTERNATIVE_TYPE_DEFINITION_COMMAND, DEFAULT_HOVER_DELAY_MS,
    DEFAULT_HOVER_HIDING_DELAY_MS, DEFAULT_INLINE_SUGGEST_FONT_FAMILY,
    DEFAULT_INLINE_SUGGEST_MIN_SHOW_DELAY_MS, DEFAULT_QUICK_SUGGESTIONS_DELAY_MS,
    DEFAULT_SCM_DIFF_DECORATIONS_GUTTER_WIDTH, DEFAULT_SCM_INPUT_FONT_FAMILY,
    DEFAULT_SCM_INPUT_FONT_SIZE, DEFAULT_SCM_REPOSITORIES_VISIBLE, DEFAULT_SUGGEST_FONT_SIZE,
    DEFAULT_SUGGEST_LINE_HEIGHT, DEFAULT_TERMINAL_ALT_CLICK_MOVES_CURSOR,
    DEFAULT_TERMINAL_BELL_DURATION_MS, DEFAULT_TERMINAL_COPY_ON_SELECTION,
    DEFAULT_TERMINAL_CURSOR_WIDTH, DEFAULT_TERMINAL_ENABLE_BELL,
    DEFAULT_TERMINAL_FAST_SCROLL_SENSITIVITY, DEFAULT_TERMINAL_FONT_SIZE,
    DEFAULT_TERMINAL_HIDE_ON_LAST_CLOSED, DEFAULT_TERMINAL_IGNORE_BRACKETED_PASTE_MODE,
    DEFAULT_TERMINAL_LETTER_SPACING, DEFAULT_TERMINAL_LINE_HEIGHT, DEFAULT_TERMINAL_MIN_COLUMNS,
    DEFAULT_TERMINAL_MIN_ROWS, DEFAULT_TERMINAL_MINIMUM_CONTRAST_RATIO,
    DEFAULT_TERMINAL_MOUSE_WHEEL_SCROLL_SENSITIVITY, DEFAULT_TERMINAL_MOUSE_WHEEL_ZOOM,
    DEFAULT_TERMINAL_SCROLLBACK_ROWS, DEFAULT_TERMINAL_SHOW_EXIT_ALERT,
    DEFAULT_TERMINAL_TABS_ALLOW_AGENT_CLI_TITLE, DEFAULT_TERMINAL_TABS_DEFAULT_ICON,
    DEFAULT_TERMINAL_TABS_ENABLED, DEFAULT_TERMINAL_TABS_TITLE, DEFAULT_TERMINAL_WORD_SEPARATORS,
    DEFAULT_WINDOW_ZOOM_LEVEL, DiffWordWrap, EDITOR_FONT_LIGATURES_ON,
    EDITOR_FONT_VARIATIONS_TRANSLATE, EditorAccessibilitySupport, EditorAutoClosingEditStrategy,
    EditorAutoClosingStrategy, EditorAutoSaveMode, EditorBracketPairGuideMode,
    EditorColorDecoratorsActivatedOn, EditorCursorSmoothCaretAnimation, EditorCursorStyle,
    EditorCursorSurroundingLinesStyle, EditorDefaultColorDecorators,
    EditorDropIntoEditorShowDropSelector, EditorExperimentalGpuAcceleration,
    EditorExperimentalWhitespaceRendering, EditorFindAutoFindInSelection, EditorFindHistory,
    EditorFindSeedSearchStringFromSelection, EditorFoldingStrategy, EditorGotoLocationMultiple,
    EditorHighlightActiveIndentation, EditorInlineSuggestEditsAllowCodeShifting,
    EditorInlineSuggestEditsRenderSideBySide, EditorInlineSuggestMode,
    EditorInlineSuggestShowOnSuggestConflict, EditorInlineSuggestShowToolbar, EditorLightbulbMode,
    EditorLineDecorationsWidth, EditorLineNumbers, EditorMatchBrackets, EditorMinimapAutohide,
    EditorMinimapShowSlider, EditorMinimapSide, EditorMinimapSize, EditorMouseMiddleClickAction,
    EditorMouseStyle, EditorMultiCursorModifier, EditorMultiCursorPaste,
    EditorPasteAsShowPasteSelector, EditorPeekWidgetDefaultFocus, EditorRenderFinalNewline,
    EditorRenderLineHighlight, EditorRenderValidationDecorations, EditorRenderWhitespace,
    EditorScrollbarVisibility, EditorSettings, EditorSettingsLoad, EditorShowFoldingControls,
    EditorSnippetSuggestions, EditorStickyScrollDefaultModel, EditorSuggestInsertMode,
    EditorSuggestPreviewMode, EditorSuggestSelection, EditorSuggestSelectionMode,
    EditorTabCompletion, EditorUnicodeHighlightNonBasicAscii, EditorUnicodeHighlightScope,
    EditorUnusualLineTerminators, EditorVimKeyOverride, EditorVimSettings, EditorWordBreak,
    EditorWordWrap, EditorWordWrapOverride, EditorWrappingIndent, EditorWrappingStrategy,
    GitAddAiCoAuthor, GitAutoFetch, GitAutoRepositoryDetection, GitBranchProtectionPrompt,
    GitBranchSortOrder, GitCountBadge, GitInputValidationSubjectLength, GitOpenAfterClone,
    GitOpenRepositoryInParentFolders, GitPostCommitCommand, GitPromptToSaveFilesBeforeCommit,
    GitUntrackedChanges, MAX_AUTOSAVE_DELAY_MS, MAX_DIFF_RENDER_SIDE_BY_SIDE_INLINE_BREAKPOINT,
    MAX_DIFF_SPLIT_VIEW_DEFAULT_RATIO, MAX_EDITOR_ACCESSIBILITY_PAGE_SIZE,
    MAX_EDITOR_CODE_LENS_FONT_SIZE, MAX_EDITOR_COLOR_DECORATORS_LIMIT, MAX_EDITOR_CURSOR_HEIGHT,
    MAX_EDITOR_CURSOR_SURROUNDING_LINES, MAX_EDITOR_CURSOR_WIDTH,
    MAX_EDITOR_FOLDING_MAXIMUM_REGIONS, MAX_EDITOR_INLAY_HINTS_FONT_SIZE,
    MAX_EDITOR_INLAY_HINTS_MAXIMUM_LENGTH, MAX_EDITOR_LETTER_SPACING,
    MAX_EDITOR_LINE_DECORATIONS_WIDTH, MAX_EDITOR_LINE_HEIGHT, MAX_EDITOR_LINE_NUMBERS_MIN_CHARS,
    MAX_EDITOR_MINIMAP_MAX_COLUMN, MAX_EDITOR_MINIMAP_SCALE,
    MAX_EDITOR_MINIMAP_SECTION_HEADER_FONT_SIZE, MAX_EDITOR_MINIMAP_SECTION_HEADER_LETTER_SPACING,
    MAX_EDITOR_MULTI_CURSOR_LIMIT, MAX_EDITOR_OVERVIEW_RULER_LANES, MAX_EDITOR_PADDING,
    MAX_EDITOR_REVEAL_HORIZONTAL_RIGHT_PADDING, MAX_EDITOR_RULER_COLUMN,
    MAX_EDITOR_SCROLL_BEYOND_LAST_COLUMN, MAX_EDITOR_SCROLL_SENSITIVITY, MAX_EDITOR_SCROLLBAR_SIZE,
    MAX_EDITOR_STICKY_SCROLL_MAX_LINE_COUNT, MAX_EDITOR_STOP_RENDERING_LINE_AFTER,
    MAX_EDITOR_TAB_INDEX, MAX_EDITOR_WORD_WRAP_COLUMN, MAX_GIT_AUTOFETCH_PERIOD,
    MAX_GIT_DETECT_WORKTREES_LIMIT, MAX_GIT_INPUT_VALIDATION_LENGTH,
    MAX_GIT_REPOSITORY_SCAN_MAX_DEPTH, MAX_HOVER_DELAY_MS, MAX_HOVER_HIDING_DELAY_MS,
    MAX_INLINE_SUGGEST_MIN_SHOW_DELAY_MS, MAX_QUICK_SUGGESTIONS_DELAY_MS,
    MAX_SCM_DIFF_DECORATIONS_GUTTER_WIDTH, MAX_SCM_GRAPH_PAGE_SIZE, MAX_SCM_INPUT_FONT_SIZE,
    MAX_SCM_INPUT_LINE_COUNT, MAX_SCM_REPOSITORIES_VISIBLE, MAX_SUGGEST_FONT_SIZE,
    MAX_SUGGEST_LINE_HEIGHT, MAX_TERMINAL_BELL_DURATION_MS, MAX_TERMINAL_CURSOR_WIDTH,
    MAX_TERMINAL_FONT_SIZE, MAX_TERMINAL_LETTER_SPACING, MAX_TERMINAL_LINE_HEIGHT,
    MAX_TERMINAL_MIN_COLUMNS, MAX_TERMINAL_MIN_ROWS, MAX_TERMINAL_MINIMUM_CONTRAST_RATIO,
    MAX_TERMINAL_SCROLL_SENSITIVITY, MAX_TERMINAL_SCROLLBACK_ROWS, MAX_WINDOW_ZOOM_LEVEL,
    MIN_AUTOSAVE_DELAY_MS, MIN_DIFF_RENDER_SIDE_BY_SIDE_INLINE_BREAKPOINT,
    MIN_DIFF_SPLIT_VIEW_DEFAULT_RATIO, MIN_EDITOR_ACCESSIBILITY_PAGE_SIZE,
    MIN_EDITOR_CODE_LENS_FONT_SIZE, MIN_EDITOR_COLOR_DECORATORS_LIMIT, MIN_EDITOR_CURSOR_HEIGHT,
    MIN_EDITOR_CURSOR_WIDTH, MIN_EDITOR_FOLDING_MAXIMUM_REGIONS, MIN_EDITOR_INLAY_HINTS_FONT_SIZE,
    MIN_EDITOR_INLAY_HINTS_MAXIMUM_LENGTH, MIN_EDITOR_LETTER_SPACING,
    MIN_EDITOR_LINE_DECORATIONS_WIDTH, MIN_EDITOR_LINE_HEIGHT, MIN_EDITOR_LINE_NUMBERS_MIN_CHARS,
    MIN_EDITOR_MINIMAP_MAX_COLUMN, MIN_EDITOR_MINIMAP_SCALE,
    MIN_EDITOR_MINIMAP_SECTION_HEADER_FONT_SIZE, MIN_EDITOR_MINIMAP_SECTION_HEADER_LETTER_SPACING,
    MIN_EDITOR_MULTI_CURSOR_LIMIT, MIN_EDITOR_OVERVIEW_RULER_LANES, MIN_EDITOR_PADDING,
    MIN_EDITOR_REVEAL_HORIZONTAL_RIGHT_PADDING, MIN_EDITOR_SCROLL_BEYOND_LAST_COLUMN,
    MIN_EDITOR_SCROLL_SENSITIVITY, MIN_EDITOR_SCROLLBAR_SIZE,
    MIN_EDITOR_STICKY_SCROLL_MAX_LINE_COUNT, MIN_EDITOR_STOP_RENDERING_LINE_AFTER,
    MIN_EDITOR_TAB_INDEX, MIN_EDITOR_WORD_WRAP_COLUMN, MIN_GIT_AUTOFETCH_PERIOD,
    MIN_GIT_DETECT_WORKTREES_LIMIT, MIN_GIT_INPUT_VALIDATION_LENGTH,
    MIN_GIT_REPOSITORY_SCAN_MAX_DEPTH, MIN_HOVER_DELAY_MS, MIN_HOVER_HIDING_DELAY_MS,
    MIN_INLINE_SUGGEST_MIN_SHOW_DELAY_MS, MIN_QUICK_SUGGESTIONS_DELAY_MS,
    MIN_SCM_DIFF_DECORATIONS_GUTTER_WIDTH, MIN_SCM_GRAPH_PAGE_SIZE, MIN_SCM_INPUT_FONT_SIZE,
    MIN_SCM_INPUT_LINE_COUNT, MIN_SCM_REPOSITORIES_VISIBLE, MIN_SUGGEST_FONT_SIZE,
    MIN_SUGGEST_LINE_HEIGHT, MIN_TERMINAL_BELL_DURATION_MS, MIN_TERMINAL_CURSOR_WIDTH,
    MIN_TERMINAL_FONT_SIZE, MIN_TERMINAL_LETTER_SPACING, MIN_TERMINAL_LINE_HEIGHT,
    MIN_TERMINAL_MIN_COLUMNS, MIN_TERMINAL_MIN_ROWS, MIN_TERMINAL_MINIMUM_CONTRAST_RATIO,
    MIN_TERMINAL_SCROLL_SENSITIVITY, MIN_TERMINAL_SCROLLBACK_ROWS, MIN_WINDOW_ZOOM_LEVEL,
    SETTINGS_SCHEMA_VERSION, ScmCountBadge, ScmDefaultViewMode, ScmDefaultViewSortKey,
    ScmDiffDecorations, ScmDiffDecorationsGutterAction, ScmDiffDecorationsGutterPattern,
    ScmDiffDecorationsGutterVisibility, ScmDiffDecorationsIgnoreTrimWhitespace, ScmGraphBadges,
    ScmProviderCountBadge, TerminalConfirmOnExit, TerminalConfirmOnKill, TerminalCursorStyle,
    TerminalHideOnStartup, TerminalInactiveCursorStyle, TerminalMiddleClickBehavior,
    TerminalMultiLinePasteWarning, TerminalRightClickBehavior, TerminalSplitCwd,
    TerminalTabsFocusMode, TerminalTabsHideCondition, TerminalTabsLocation,
    TerminalTabsShowActions, TerminalTabsShowActiveTerminal, ThemeSettings,
    clamp_autosave_delay_ms, clamp_diff_render_side_by_side_inline_breakpoint,
    clamp_diff_split_view_default_ratio, clamp_editor_accessibility_page_size,
    clamp_editor_code_lens_font_size, clamp_editor_color_decorators_limit,
    clamp_editor_cursor_height, clamp_editor_cursor_surrounding_lines, clamp_editor_cursor_width,
    clamp_editor_folding_maximum_regions, clamp_editor_inlay_hints_font_size,
    clamp_editor_inlay_hints_maximum_length, clamp_editor_letter_spacing,
    clamp_editor_line_decorations_width, clamp_editor_line_height,
    clamp_editor_line_numbers_min_chars, clamp_editor_minimap_max_column,
    clamp_editor_minimap_scale, clamp_editor_minimap_section_header_font_size,
    clamp_editor_minimap_section_header_letter_spacing, clamp_editor_multi_cursor_limit,
    clamp_editor_overview_ruler_lanes, clamp_editor_padding,
    clamp_editor_reveal_horizontal_right_padding, clamp_editor_ruler_column,
    clamp_editor_scroll_beyond_last_column, clamp_editor_scroll_sensitivity,
    clamp_editor_scrollbar_size, clamp_editor_sticky_scroll_max_line_count,
    clamp_editor_stop_rendering_line_after, clamp_editor_tab_index, clamp_editor_word_wrap_column,
    clamp_git_autofetch_period, clamp_git_detect_worktrees_limit,
    clamp_git_input_validation_length, clamp_git_repository_scan_max_depth, clamp_hover_delay_ms,
    clamp_hover_hiding_delay_ms, clamp_inline_suggest_min_show_delay_ms,
    clamp_quick_suggestions_delay_ms, clamp_scm_diff_decorations_gutter_width,
    clamp_scm_graph_page_size, clamp_scm_input_font_size, clamp_scm_input_line_count,
    clamp_scm_repositories_visible, clamp_suggest_font_size, clamp_suggest_line_height,
    clamp_terminal_bell_duration_ms, clamp_terminal_cursor_width, clamp_terminal_font_size,
    clamp_terminal_letter_spacing, clamp_terminal_line_height, clamp_terminal_min_columns,
    clamp_terminal_min_rows, clamp_terminal_minimum_contrast_ratio,
    clamp_terminal_scroll_sensitivity, clamp_terminal_scrollback_rows, clamp_window_zoom_level,
    editor_stop_rendering_line_after_limit, git_branch_validation_error,
    minimap_section_header_lines, normalize_editor_font_ligatures,
    normalize_editor_font_variations, sanitize_editor_font_weight, window_zoom_factor,
};
pub use syntax::{LanguageBracketPair, LanguageConfiguration, LanguageId};
pub use tasks::{
    WorkspaceTask, WorkspaceTaskKind, inferred_workspace_tasks, load_workspace_tasks,
    parse_workspace_tasks_toml, workspace_task_command_preview, workspace_task_default_index,
    workspace_task_kind_label, workspace_task_kind_title, workspace_tasks_path,
};
pub use workspace_paths::normalize_child_path;
