mod completion;
mod dirty_guards;
mod lsp_sync;
mod queues;
mod save_plans;

use crate::{
    layout::{
        DIAGNOSTICS_PANEL_DEFAULT_WIDTH, EXPLORER_DEFAULT_WIDTH, PROJECT_SEARCH_DEFAULT_WIDTH,
        SOURCE_CONTROL_DEFAULT_WIDTH, SYMBOLS_PANEL_DEFAULT_WIDTH, TERMINAL_DEFAULT_HEIGHT,
    },
    panel_layout::PanelPlacement,
    persistence::{
        PersistedSession, PersistedSourceControlSortMode, PersistedSourceControlViewMode,
        PersistedTerminalSession,
    },
};
use std::path::Path;

fn session_for_test(root: &Path, marker: &str) -> PersistedSession {
    PersistedSession {
        workspace_root: root.to_path_buf(),
        open_files: vec![root.join(marker)],
        active_path: Some(root.join(marker)),
        pane_paths: vec![Some(root.join(marker))],
        pane_weights: vec![1.0],
        active_pane_index: Some(0),
        view_states: Vec::new(),
        pane_view_states: Vec::new(),
        history_states: Vec::new(),
        recovery_view_states: Vec::new(),
        recovery_history_states: Vec::new(),
        fold_states: Vec::new(),
        explorer_width: EXPLORER_DEFAULT_WIDTH,
        explorer_expanded: Vec::new(),
        explorer_revealed_path: None,
        project_search_open: false,
        project_search_placement: PanelPlacement::DockedRight,
        project_search_width: PROJECT_SEARCH_DEFAULT_WIDTH,
        project_search_query: String::new(),
        project_search_case_sensitive: false,
        project_search_whole_word: false,
        project_search_include: String::new(),
        project_search_exclude: String::new(),
        project_search_recent: Vec::new(),
        buffer_find_open: false,
        buffer_find_query: String::new(),
        buffer_find_replacement: String::new(),
        buffer_find_case_sensitive: false,
        buffer_find_whole_word: false,
        buffer_find_regex: false,
        buffer_find_preserve_case: false,
        buffer_find_query_history: Vec::new(),
        buffer_find_replacement_history: Vec::new(),
        settings_panel_open: false,
        theme_picker_open: false,
        keybindings_open: false,
        symbols_panel_open: false,
        symbols_panel_placement: PanelPlacement::DockedRight,
        symbols_panel_width: SYMBOLS_PANEL_DEFAULT_WIDTH,
        diagnostics_panel_open: false,
        diagnostics_panel_placement: PanelPlacement::DockedRight,
        diagnostics_panel_width: DIAGNOSTICS_PANEL_DEFAULT_WIDTH,
        source_control_open: false,
        source_control_placement: PanelPlacement::DockedRight,
        source_control_width: SOURCE_CONTROL_DEFAULT_WIDTH,
        source_control_query: String::new(),
        source_control_view: PersistedSourceControlViewMode::default(),
        source_control_sort: PersistedSourceControlSortMode::default(),
        source_control_commit_message: String::new(),
        source_control_commit_history: Vec::new(),
        source_control_stash_message: String::new(),
        source_control_stashes_open: false,
        source_control_history_open: false,
        source_control_history_query: String::new(),
        source_control_unstaged_collapsed: false,
        source_control_untracked_collapsed: false,
        source_control_staged_collapsed: false,
        terminal_visible: true,
        terminal_height: TERMINAL_DEFAULT_HEIGHT,
        terminal_sessions: vec![PersistedTerminalSession {
            cwd: Some(root.to_path_buf()),
            scrollback: String::new(),
            scrollback_offset: 0,
            custom_title: None,
            process_label: None,
            process_status: None,
            window_title: None,
        }],
        terminal_active_session: 0,
        terminal_split_view: false,
        terminal_split_weights: vec![1.0],
        recent_projects: vec![root.to_path_buf()],
        quick_open_recent_files: Vec::new(),
        quick_open_query_memory: Vec::new(),
        workspace_symbol_query_memory: Vec::new(),
        command_recent: Vec::new(),
        command_query_memory: Vec::new(),
        navigation_back: Vec::new(),
        navigation_forward: Vec::new(),
        closed_files: Vec::new(),
        recovery: Vec::new(),
        recovery_skipped: Vec::new(),
    }
}
